[Variables]

; -------------------------------------

; Adjust as necessary
body.ElementSize=30
body.Padding=8
body.CornerRadius=6
body.PopUpGap=5

; -------------------------------------

; Do not adjust

; Background
colour.1.Code=35,35,35
colour.1.Alpha=255
; Element
colour.2.Code=200,200,200
colour.2.Alpha=255
; Highlight
colour.3.Code=220,220,220
colour.3.Alpha=20

; -------------------------------------

; Adjustable but not recommended
font.DisplayName=Inconsolata
font.SizeStd=(#body.ElementSize#*1/3)

; Do not adjust
font.IconName=MaterialIcon

; -------------------------------------

; Do not adjust
body.Verticality=1
body.X=212
body.Y=1106
body.Height=46
body.Width=1500
ActiveModules=Battery,Start,Taskbar,Time,Volume
AvaliableModules=Battery,NowPlaying,Power,Start,Taskbar,Time,Volume,WSM
