[Variables]
Bar_Opacity=00
Bar_Width =1920
Bar_Height =32
Bar_OffsetX =0
Bar_OffsetY =12

Section_Height =40
Section_Padding = 12

Color_Scheme1 =000000
Color_Scheme2 =FFF3E6
Color_Scheme3 =000000
Color_Scheme4 =FFFFFF
Color_Scheme5 =FFFFFF

Font_Face1=Consolas
Font_Face2=Consolas
Font_Size=9

Shadow=0
Translucent=0
DefaultAddedModules=startmenu,tray,music,time,date,volume,taskbar,weather,netspeed

