
[Shape]
Meter=Shape
DynamicVariables=1
W=146
H=152
TransformationMatrix=1;0;0;1;0;0

Shape=Rectangle 0, (152+(-1*(50)*[Measure1])), 2, (-1*(2+100*[Measure1])), 0 | Fill Color 237,237,237,255 | StrokeWidth 0 | Stroke Color 26,255,241

Shape2=Rectangle 16, (152+(-1*(50)*[Measure2])), 2, (-1*(2+100*[Measure2])), 0 | Fill Color 237,237,237,255 | StrokeWidth 0 | Stroke Color 26,255,241

Shape3=Rectangle 32, (152+(-1*(50)*[Measure3])), 2, (-1*(2+100*[Measure3])), 0 | Fill Color 237,237,237,255 | StrokeWidth 0 | Stroke Color 26,255,241

Shape4=Rectangle 48, (152+(-1*(50)*[Measure4])), 2, (-1*(2+100*[Measure4])), 0 | Fill Color 237,237,237,255 | StrokeWidth 0 | Stroke Color 26,255,241

Shape5=Rectangle 64, (152+(-1*(50)*[Measure5])), 2, (-1*(2+100*[Measure5])), 0 | Fill Color 237,237,237,255 | StrokeWidth 0 | Stroke Color 26,255,241

Shape6=Rectangle 80, (152+(-1*(50)*[Measure6])), 2, (-1*(2+100*[Measure6])), 0 | Fill Color 237,237,237,255 | StrokeWidth 0 | Stroke Color 26,255,241

Shape7=Rectangle 96, (152+(-1*(50)*[Measure7])), 2, (-1*(2+100*[Measure7])), 0 | Fill Color 237,237,237,255 | StrokeWidth 0 | Stroke Color 26,255,241

Shape8=Rectangle 112, (152+(-1*(50)*[Measure8])), 2, (-1*(2+100*[Measure8])), 0 | Fill Color 237,237,237,255 | StrokeWidth 0 | Stroke Color 26,255,241

Shape9=Rectangle 128, (152+(-1*(50)*[Measure9])), 2, (-1*(2+100*[Measure9])), 0 | Fill Color 237,237,237,255 | StrokeWidth 0 | Stroke Color 26,255,241

Shape10=Rectangle 144, (152+(-1*(50)*[Measure10])), 2, (-1*(2+100*[Measure10])), 0 | Fill Color 237,237,237,255 | StrokeWidth 0 | Stroke Color 26,255,241

